spring:
  application:
    name: myApp
  cloud:
    consul:
      config:
        enabled: false
      discovery:
        instanceId: ${spring.application.name}:'dangnt':${random.value}
        healthCheckPath: /my-health-check
        healthCheckInterval: 3s

#      host: localhost
#      port: 8500
#      discovery:
#        instanceId: ${spring.application.name}:${random.value}
